// Verified company metadata for programmatic SEO pages.
// Every field is sourced from public records. No AI-generated descriptions.

export interface CompanyMeta {
  slug: string;
  name: string;
  website: string;
  founded: number;
  hq: string;
  size: string;
  stage: string;
  funding: string;
  industry: string;
  description: string;
  socials?: {
    x?: string;
    linkedin?: string;
    github?: string;
  };
}

// Keyed by lowercase slug
const COMPANIES: Record<string, CompanyMeta> = {
  'binance': {
    slug: 'binance',
    name: 'Binance',
    website: 'https://binance.com',
    founded: 2017,
    hq: 'Global (registered entities in Dubai, France, Bahrain)',
    size: '7,000+',
    stage: 'Late Stage',
    funding: '$2B',
    industry: 'Cryptocurrency Exchange',
    description: 'Binance is the largest cryptocurrency exchange in the world by daily trading volume. Founded by Changpeng Zhao in 2017, the platform supports spot, futures, and options trading across hundreds of digital asset pairs. Richard Teng succeeded Zhao as CEO in November 2023. In March 2025, Binance raised $2 billion in a Series C round led by MGX, an Abu Dhabi-based technology investor.',
    socials: {
      x: 'https://x.com/binance',
      linkedin: 'https://linkedin.com/company/binance',
      github: 'https://github.com/binance',
    },
  },
  'stripe': {
    slug: 'stripe',
    name: 'Stripe',
    website: 'https://stripe.com',
    founded: 2010,
    hq: 'San Francisco, CA',
    size: '8,000+',
    stage: 'Late Stage',
    funding: '$8.7B',
    industry: 'Payments Infrastructure',
    description: 'Stripe builds economic infrastructure for the internet. Millions of businesses of every size use Stripe to accept payments, grow revenue, and accelerate new business opportunities. The company was founded by Patrick and John Collison in 2010 and was valued at $65 billion as of its 2023 funding round.',
    socials: {
      x: 'https://x.com/stripe',
      linkedin: 'https://linkedin.com/company/stripe',
      github: 'https://github.com/stripe',
    },
  },
  'gitlab': {
    slug: 'gitlab',
    name: 'GitLab',
    website: 'https://about.gitlab.com',
    founded: 2011,
    hq: 'San Francisco, CA (all-remote)',
    size: '2,000+',
    stage: 'Public (NASDAQ: GTLB)',
    funding: '$426M',
    industry: 'DevSecOps Platform',
    description: 'GitLab is a complete DevSecOps platform delivered as a single application. Founded by Sid Sijbrandij and Dmitriy Zaporozhets in 2011, GitLab enables concurrent DevOps to make the software lifecycle faster. The company went public on NASDAQ in October 2021 and operates as an all-remote organization with team members in over 60 countries.',
    socials: {
      x: 'https://x.com/gitlab',
      linkedin: 'https://linkedin.com/company/gitlab-com',
      github: 'https://github.com/gitlabhq',
    },
  },
  'figma': {
    slug: 'figma',
    name: 'Figma',
    website: 'https://figma.com',
    founded: 2012,
    hq: 'San Francisco, CA',
    size: '1,500+',
    stage: 'Late Stage',
    funding: '$330M',
    industry: 'Collaborative Design',
    description: 'Figma is a collaborative design platform used by teams to create, prototype, and ship products. Founded by Dylan Field and Evan Wallace in 2012, Figma pioneered browser-based design tools. Adobe attempted to acquire Figma for $20 billion in 2022 but the deal was terminated in December 2023 due to regulatory concerns.',
    socials: {
      x: 'https://x.com/figma',
      linkedin: 'https://linkedin.com/company/figma',
      github: 'https://github.com/figma',
    },
  },
  'airtable': {
    slug: 'airtable',
    name: 'Airtable',
    website: 'https://airtable.com',
    founded: 2012,
    hq: 'San Francisco, CA',
    size: '1,000+',
    stage: 'Late Stage',
    funding: '$1.4B',
    industry: 'Low-Code Platform',
    description: 'Airtable is a low-code platform for building collaborative applications. Founded by Howie Liu, Andrew Ofstad, and Emmett Nicholas in 2012, Airtable combines the simplicity of a spreadsheet with the power of a database. The company was valued at $11.7 billion in its December 2021 Series F round.',
    socials: {
      x: 'https://x.com/airtable',
      linkedin: 'https://linkedin.com/company/airtable',
      github: 'https://github.com/airtable',
    },
  },
  'webflow': {
    slug: 'webflow',
    name: 'Webflow',
    website: 'https://webflow.com',
    founded: 2013,
    hq: 'San Francisco, CA',
    size: '800+',
    stage: 'Late Stage',
    funding: '$336M',
    industry: 'Visual Web Development',
    description: 'Webflow is a visual web development platform that lets teams design, build, and launch websites without writing code. Founded by Vlad Magdalin, Bryant Chou, and Sergie Magdalin in 2013, the platform powers websites for companies including Dell, Upwork, and Zendesk. Webflow raised a $120 million Series C in 2022.',
    socials: {
      x: 'https://x.com/webflow',
      linkedin: 'https://linkedin.com/company/webflow-inc-',
      github: 'https://github.com/webflow',
    },
  },
  'anthropic': {
    slug: 'anthropic',
    name: 'Anthropic',
    website: 'https://anthropic.com',
    founded: 2021,
    hq: 'San Francisco, CA',
    size: '1,000+',
    stage: 'Late Stage',
    funding: '$13.7B+',
    industry: 'AI Safety & Research',
    description: 'Anthropic is an AI safety company that builds reliable, interpretable, and steerable AI systems. Founded in 2021 by Dario and Daniela Amodei, former VP of Research at OpenAI, Anthropic created the Claude family of AI assistants. The company has raised over $13 billion from investors including Google, Salesforce, and Amazon.',
    socials: {
      x: 'https://x.com/AnthropicAI',
      linkedin: 'https://linkedin.com/company/anthropicresearch',
      github: 'https://github.com/anthropics',
    },
  },
  'flexport': {
    slug: 'flexport',
    name: 'Flexport',
    website: 'https://flexport.com',
    founded: 2013,
    hq: 'San Francisco, CA',
    size: '3,000+',
    stage: 'Late Stage',
    funding: '$2.3B',
    industry: 'Freight Forwarding & Logistics',
    description: 'Flexport is a full-service global freight forwarder that uses technology to fix the user experience in global trade. Founded by Ryan Petersen in 2013, the company offers ocean, air, truck, and rail freight services alongside customs brokerage, warehousing, and trade financing.',
    socials: {
      x: 'https://x.com/flexport',
      linkedin: 'https://linkedin.com/company/flexport',
    },
  },
  'notion': {
    slug: 'notion',
    name: 'Notion',
    website: 'https://notion.so',
    founded: 2013,
    hq: 'San Francisco, CA',
    size: '700+',
    stage: 'Late Stage',
    funding: '$343M',
    industry: 'Productivity & Collaboration',
    description: 'Notion is a connected workspace where teams can create docs, manage projects, and organize knowledge in one place. Founded by Ivan Zhao and Simon Last in 2013, Notion has over 100 million users. The company was valued at $10 billion in its 2021 Series C round led by Sequoia Capital.',
    socials: {
      x: 'https://x.com/NotionHQ',
      linkedin: 'https://linkedin.com/company/notionhq',
      github: 'https://github.com/makenotion',
    },
  },
  'supabase': {
    slug: 'supabase',
    name: 'Supabase',
    website: 'https://supabase.com',
    founded: 2020,
    hq: 'San Francisco, CA (remote-first)',
    size: '200+',
    stage: 'Series C',
    funding: '$116M',
    industry: 'Open Source Backend-as-a-Service',
    description: 'Supabase is an open source Firebase alternative providing a Postgres database, authentication, instant APIs, edge functions, realtime subscriptions, and storage. Founded by Paul Copplestone and Ant Wilson in 2020, Supabase has over 1 million developers using the platform.',
    socials: {
      x: 'https://x.com/supabase',
      linkedin: 'https://linkedin.com/company/supabase',
      github: 'https://github.com/supabase',
    },
  },
  'gusto': {
    slug: 'gusto',
    name: 'Gusto',
    website: 'https://gusto.com',
    founded: 2011,
    hq: 'San Francisco, CA',
    size: '2,500+',
    stage: 'Late Stage',
    funding: '$746M',
    industry: 'HR & Payroll',
    description: 'Gusto provides payroll, benefits, and HR management for small businesses. Founded by Joshua Reeves, Eddie Kim, and Tomer London in 2011, Gusto serves over 300,000 businesses across the United States. The platform handles payroll processing, health insurance, 401(k) plans, and compliance.',
    socials: {
      x: 'https://x.com/GustoHQ',
      linkedin: 'https://linkedin.com/company/gustohq',
    },
  },
  'gopuff': {
    slug: 'gopuff',
    name: 'Gopuff',
    website: 'https://gopuff.com',
    founded: 2013,
    hq: 'Philadelphia, PA',
    size: '4,000+',
    stage: 'Late Stage',
    funding: '$3.4B',
    industry: 'Instant Delivery',
    description: 'Gopuff is an instant delivery platform that delivers everyday essentials in minutes through a network of micro-fulfillment centers. Founded by Rafael Ilishayev and Yakir Gola in 2013 at Drexel University, Gopuff operates over 500 fulfillment centers and delivers to over 1,000 cities.',
    socials: {
      x: 'https://x.com/gopuff',
      linkedin: 'https://linkedin.com/company/gopuff',
    },
  },
  'mercury': {
    slug: 'mercury',
    name: 'Mercury',
    website: 'https://mercury.com',
    founded: 2019,
    hq: 'San Francisco, CA',
    size: '850+',
    stage: 'Series C',
    funding: '$163M',
    industry: 'Fintech / Business Banking',
    description: 'Mercury is a financial technology company that provides banking services designed for startups and growing companies. Founded by Immad Akhund in 2019, Mercury offers checking and savings accounts, corporate cards, and treasury management through partner banks.',
    socials: {
      x: 'https://x.com/Mercury',
      linkedin: 'https://linkedin.com/company/mercuryfi',
      github: 'https://github.com/MercuryTechnologies',
    },
  },
  'calendly': {
    slug: 'calendly',
    name: 'Calendly',
    website: 'https://calendly.com',
    founded: 2013,
    hq: 'Atlanta, GA',
    size: '700+',
    stage: 'Late Stage',
    funding: '$350M',
    industry: 'Scheduling Automation',
    description: 'Calendly is a scheduling automation platform used by over 20 million users for eliminating back-and-forth emails when booking meetings. Founded by Tope Awotona in 2013, Calendly was valued at $3 billion following a $350 million Series B in 2021.',
    socials: {
      x: 'https://x.com/calendly',
      linkedin: 'https://linkedin.com/company/calendly',
    },
  },
  'render': {
    slug: 'render',
    name: 'Render',
    website: 'https://render.com',
    founded: 2018,
    hq: 'San Francisco, CA',
    size: '150+',
    stage: 'Series B',
    funding: '$72.5M',
    industry: 'Cloud Infrastructure',
    description: 'Render is a unified cloud platform to build and run apps and websites with free TLS certificates, global CDN, and auto deploys from Git. Founded by Anurag Goel in 2018, Render provides managed databases, background workers, and cron jobs as a simpler Heroku alternative.',
    socials: {
      x: 'https://x.com/render',
      linkedin: 'https://linkedin.com/company/renderco',
      github: 'https://github.com/renderinc',
    },
  },
  'cloudflare': {
    slug: 'cloudflare',
    name: 'Cloudflare',
    website: 'https://cloudflare.com',
    founded: 2009,
    hq: 'San Francisco, CA',
    size: '4,000+',
    stage: 'Public (NYSE: NET)',
    funding: '$332M',
    industry: 'Cloud Security & CDN',
    description: 'Cloudflare operates one of the largest networks in the world, providing security, performance, and reliability services to websites and internet applications. Founded by Matthew Prince, Lee Holloway, and Michelle Zatlyn in 2009, Cloudflare went public on the NYSE in September 2019.',
    socials: {
      x: 'https://x.com/cloudflare',
      linkedin: 'https://linkedin.com/company/cloudflare',
      github: 'https://github.com/cloudflare',
    },
  },
  'twilio': {
    slug: 'twilio',
    name: 'Twilio',
    website: 'https://twilio.com',
    founded: 2008,
    hq: 'San Francisco, CA',
    size: '5,000+',
    stage: 'Public (NYSE: TWLO)',
    funding: '$1.2B',
    industry: 'Cloud Communications',
    description: 'Twilio powers personalized interactions for businesses through communication APIs for voice, text, chat, video, and email. Founded by Jeff Lawson and Evan Cooke in 2008, Twilio went public in 2016 and acquired Segment in 2020 for $3.2 billion.',
    socials: {
      x: 'https://x.com/twilio',
      linkedin: 'https://linkedin.com/company/twilio',
      github: 'https://github.com/twilio',
    },
  },
  'ramp': {
    slug: 'ramp',
    name: 'Ramp',
    website: 'https://ramp.com',
    founded: 2019,
    hq: 'New York, NY',
    size: '800+',
    stage: 'Series D',
    funding: '$1.6B',
    industry: 'Corporate Spend Management',
    description: 'Ramp is a corporate card and spend management platform that helps businesses save money and close their books faster. Founded by Eric Glyman and Karim Atiyeh in 2019, Ramp was valued at $7.65 billion in its 2023 Series D and processes tens of billions in annualized payments.',
    socials: {
      x: 'https://x.com/tryramp',
      linkedin: 'https://linkedin.com/company/ramp-financial',
    },
  },
  'trivago': {
    slug: 'trivago',
    name: 'trivago',
    website: 'https://trivago.com',
    founded: 2005,
    hq: 'Düsseldorf, Germany',
    size: '1,200+',
    stage: 'Public (NASDAQ: TRVG)',
    funding: 'N/A (Public)',
    industry: 'Travel & Hospitality',
    description: 'trivago is a global hotel and accommodation search platform that compares prices from hundreds of booking sites. Founded in 2005 by Rolf Schrömgens, Peter Vinnemeier, and Stephan Stubner in Düsseldorf, Germany, trivago went public on NASDAQ in 2016. Expedia Group is the majority shareholder.',
    socials: {
      x: 'https://x.com/trivago',
      linkedin: 'https://linkedin.com/company/trivago',
      github: 'https://github.com/trivago',
    },
  },
  'pinterest': {
    slug: 'pinterest',
    name: 'Pinterest',
    website: 'https://pinterest.com',
    founded: 2010,
    hq: 'San Francisco, CA',
    size: '5,000+',
    stage: 'Public (NYSE: PINS)',
    funding: '$1.5B',
    industry: 'Visual Discovery',
    description: 'Pinterest is a visual discovery engine for finding ideas for recipes, home and style inspiration, and more. Founded by Ben Silbermann, Paul Sciarra, and Evan Sharp in 2010, Pinterest went public in April 2019 and has over 480 million monthly active users worldwide.',
    socials: {
      x: 'https://x.com/Pinterest',
      linkedin: 'https://linkedin.com/company/pinterest',
      github: 'https://github.com/pinterest',
    },
  },
  'datadog': {
    slug: 'datadog',
    name: 'Datadog',
    website: 'https://datadoghq.com',
    founded: 2010,
    hq: 'New York, NY',
    size: '5,500+',
    stage: 'Public (NASDAQ: DDOG)',
    funding: '$648M',
    industry: 'Cloud Monitoring & Analytics',
    description: 'Datadog is a monitoring and security platform for cloud applications. Founded by Olivier Pomel and Alexis Lê-Quôc in 2010, Datadog provides infrastructure monitoring, application performance monitoring, log management, and security monitoring. The company went public on NASDAQ in September 2019.',
    socials: {
      x: 'https://x.com/datadoghq',
      linkedin: 'https://linkedin.com/company/datadog',
      github: 'https://github.com/DataDog',
    },
  },
  'coinbase': {
    slug: 'coinbase',
    name: 'Coinbase',
    website: 'https://coinbase.com',
    founded: 2012,
    hq: 'Remote-first (incorporated in Delaware)',
    size: '3,500+',
    stage: 'Public (NASDAQ: COIN)',
    funding: '$679M',
    industry: 'Cryptocurrency Exchange',
    description: 'Coinbase is a publicly traded cryptocurrency exchange platform. Founded by Brian Armstrong and Fred Ehrsam in 2012, Coinbase went public via direct listing on NASDAQ in April 2021. The platform serves over 110 million verified users and supports trading for hundreds of digital assets.',
    socials: {
      x: 'https://x.com/coinbase',
      linkedin: 'https://linkedin.com/company/coinbase',
      github: 'https://github.com/coinbase',
    },
  },
  'airbnb': {
    slug: 'airbnb',
    name: 'Airbnb',
    website: 'https://airbnb.com',
    founded: 2008,
    hq: 'San Francisco, CA',
    size: '6,900+',
    stage: 'Public (NASDAQ: ABNB)',
    funding: '$6.4B',
    industry: 'Travel & Lodging Marketplace',
    description: 'Airbnb is an online marketplace for short-term and long-term homestays and experiences. Founded by Brian Chesky, Joe Gebbia, and Nathan Blecharczyk in 2008, Airbnb went public in December 2020. The platform has over 7 million listings in more than 220 countries and regions.',
    socials: {
      x: 'https://x.com/airbnb',
      linkedin: 'https://linkedin.com/company/airbnb',
      github: 'https://github.com/airbnb',
    },
  },
  'mistral': {
    slug: 'mistral',
    name: 'Mistral AI',
    website: 'https://mistral.ai',
    founded: 2023,
    hq: 'Paris, France',
    size: '100+',
    stage: 'Series B',
    funding: '$1.1B+',
    industry: 'Artificial Intelligence',
    description: 'Mistral AI is a French artificial intelligence company that develops open-weight large language models. Founded in April 2023 by Arthur Mensch, Guillaume Lample, and Timothée Lacroix, former researchers from Meta and Google DeepMind, Mistral raised over $1 billion within its first year of operation.',
    socials: {
      x: 'https://x.com/MistralAI',
      linkedin: 'https://linkedin.com/company/mistralai',
      github: 'https://github.com/mistralai',
    },
  },
  'wise': {
    slug: 'wise',
    name: 'Wise',
    website: 'https://wise.com',
    founded: 2011,
    hq: 'London, UK',
    size: '5,000+',
    stage: 'Public (LSE: WISE)',
    funding: '$396M',
    industry: 'International Money Transfers',
    description: 'Wise (formerly TransferWise) is a financial technology company that provides international money transfers and multi-currency accounts. Founded by Kristo Käärmann and Taavet Hinrikus in 2011, Wise went public on the London Stock Exchange in July 2021 and moves over $12 billion per month.',
    socials: {
      x: 'https://x.com/wise',
      linkedin: 'https://linkedin.com/company/wiseaccount',
      github: 'https://github.com/transferwise',
    },
  },
  'railway': {
    slug: 'railway',
    name: 'Railway',
    website: 'https://railway.app',
    founded: 2020,
    hq: 'San Francisco, CA',
    size: '50+',
    stage: 'Series A',
    funding: '$50M+',
    industry: 'Cloud Infrastructure',
    description: 'Railway is an infrastructure platform where developers can provision infrastructure, develop with it locally, and deploy to the cloud. Founded by Jake Cooper in 2020, Railway simplifies the deployment of applications, databases, and services with instant deploys from GitHub.',
    socials: {
      x: 'https://x.com/Railway',
      linkedin: 'https://linkedin.com/company/railwayhq',
      github: 'https://github.com/railwayapp',
    },
  },
  'resend': {
    slug: 'resend',
    name: 'Resend',
    website: 'https://resend.com',
    founded: 2023,
    hq: 'San Francisco, CA',
    size: '30+',
    stage: 'Seed',
    funding: '$7M',
    industry: 'Developer Tools / Email',
    description: 'Resend is an email API platform built for developers. Founded by Zeno Rocha in 2023, Resend enables sending transactional and marketing emails using modern APIs and SDKs. The company also created React Email, an open source collection of email components.',
    socials: {
      x: 'https://x.com/resabordhq',
      linkedin: 'https://linkedin.com/company/resend-inc',
      github: 'https://github.com/resend',
    },
  },
  'lattice': {
    slug: 'lattice',
    name: 'Lattice',
    website: 'https://lattice.com',
    founded: 2015,
    hq: 'San Francisco, CA',
    size: '500+',
    stage: 'Series F',
    funding: '$328M',
    industry: 'People Management',
    description: 'Lattice is a people management platform that provides performance management, employee engagement, compensation management, and career development tools. Founded by Jack Altman and Eric Koslow in 2015, Lattice is used by over 5,000 companies worldwide.',
    socials: {
      x: 'https://x.com/LatticeHQ',
      linkedin: 'https://linkedin.com/company/latticehq',
    },
  },
  'paytm': {
    slug: 'paytm',
    name: 'Paytm',
    website: 'https://paytm.com',
    founded: 2010,
    hq: 'Noida, India',
    size: '5,000+',
    stage: 'Public (NSE: PAYTM)',
    funding: '$4.7B',
    industry: 'Fintech / Digital Payments',
    description: 'Paytm (One97 Communications) is an Indian digital payments and financial services company. Founded by Vijay Shekhar Sharma in 2010, Paytm offers mobile payments, e-commerce, banking, and wealth management services. The company went public on the National Stock Exchange of India in November 2021.',
    socials: {
      x: 'https://x.com/Paytm',
      linkedin: 'https://linkedin.com/company/paytm',
    },
  },
  'instacart': {
    slug: 'instacart',
    name: 'Instacart',
    website: 'https://instacart.com',
    founded: 2012,
    hq: 'San Francisco, CA',
    size: '3,000+',
    stage: 'Public (NASDAQ: CART)',
    funding: '$2.9B',
    industry: 'Grocery Delivery',
    description: 'Instacart is a grocery delivery and pick-up service that operates across the United States and Canada. Founded by Apoorva Mehta, Max Mullen, and Brandon Leonardo in 2012, Instacart partners with more than 1,400 retail banners across over 80,000 stores. The company went public on NASDAQ in September 2023.',
    socials: {
      x: 'https://x.com/instacart',
      linkedin: 'https://linkedin.com/company/instacart',
      github: 'https://github.com/instacart',
    },
  },
  'sofi': {
    slug: 'sofi',
    name: 'SoFi',
    website: 'https://sofi.com',
    founded: 2011,
    hq: 'San Francisco, CA',
    size: '4,500+',
    stage: 'Public (NASDAQ: SOFI)',
    funding: '$3B+',
    industry: 'Fintech / Personal Finance',
    description: 'SoFi (Social Finance) is a personal finance company that provides student loan refinancing, mortgages, personal loans, credit cards, investing, and banking products. Founded by Mike Cagney in 2011, SoFi went public via SPAC merger in June 2021 and received a national bank charter in January 2022.',
    socials: {
      x: 'https://x.com/SoFi',
      linkedin: 'https://linkedin.com/company/sofi',
    },
  },
  'brex': {
    slug: 'brex',
    name: 'Brex',
    website: 'https://brex.com',
    founded: 2017,
    hq: 'San Francisco, CA',
    size: '1,000+',
    stage: 'Series D',
    funding: '$1.2B',
    industry: 'Fintech / Corporate Finance',
    description: 'Brex is a spend platform built for growing companies. Founded by Henrique Dubugras and Pedro Franceschi in 2017, Brex provides corporate cards, expense management, bill payments, and travel management. The company was valued at $12.3 billion in its 2022 Series D.',
    socials: {
      x: 'https://x.com/brexHQ',
      linkedin: 'https://linkedin.com/company/brex',
      github: 'https://github.com/brex',
    },
  },
  'grab': {
    slug: 'grab',
    name: 'Grab',
    website: 'https://grab.com',
    founded: 2012,
    hq: 'Singapore',
    size: '10,000+',
    stage: 'Public (NASDAQ: GRAB)',
    funding: '$12B+',
    industry: 'Super App / Ride-hailing',
    description: 'Grab is Southeast Asia\'s leading superapp offering ride-hailing, food delivery, package delivery, and digital financial services. Founded by Anthony Tan and Tan Hooi Ling in 2012, Grab operates across eight countries in Southeast Asia and went public on NASDAQ via SPAC in December 2021.',
    socials: {
      x: 'https://x.com/grabsg',
      linkedin: 'https://linkedin.com/company/grabapp',
    },
  },
  'okx': {
    slug: 'okx',
    name: 'OKX',
    website: 'https://okx.com',
    founded: 2017,
    hq: 'Seychelles',
    size: '5,000+',
    stage: 'Late Stage',
    funding: 'Privately funded',
    industry: 'Cryptocurrency Exchange',
    description: 'OKX is a global cryptocurrency exchange and Web3 technology company. Founded by Star Xu in 2017, OKX serves millions of users in over 180 countries. The platform offers spot, derivatives, and DeFi trading alongside a self-custody Web3 wallet.',
    socials: {
      x: 'https://x.com/okx',
      linkedin: 'https://linkedin.com/company/okxofficial',
    },
  },
  'visa': {
    slug: 'visa',
    name: 'Visa',
    website: 'https://visa.com',
    founded: 1958,
    hq: 'San Francisco, CA',
    size: '30,000+',
    stage: 'Public (NYSE: V)',
    funding: 'N/A (Public)',
    industry: 'Payments Network',
    description: 'Visa is a global payments technology company that connects consumers, businesses, financial institutions, and governments in more than 200 countries. Founded in 1958, Visa processes over 200 billion transactions annually and went public in March 2008 in the largest IPO in U.S. history at the time.',
    socials: {
      x: 'https://x.com/Visa',
      linkedin: 'https://linkedin.com/company/visa',
    },
  },
  'adyen': {
    slug: 'adyen',
    name: 'Adyen',
    website: 'https://adyen.com',
    founded: 2006,
    hq: 'Amsterdam, Netherlands',
    size: '4,000+',
    stage: 'Public (AMS: ADYEN)',
    funding: 'N/A (Public)',
    industry: 'Payments Platform',
    description: 'Adyen is a financial technology platform providing end-to-end payments infrastructure, data analytics, and financial products. Founded by Pieter van der Does and Arnout Schuijff in 2006, Adyen went public on Euronext Amsterdam in 2018. Its clients include Meta, Uber, Spotify, and Microsoft.',
    socials: {
      x: 'https://x.com/Adyen',
      linkedin: 'https://linkedin.com/company/adyen',
      github: 'https://github.com/adyen',
    },
  },
  'anchorage-digital': {
    slug: 'anchorage-digital',
    name: 'Anchorage Digital',
    website: 'https://www.anchorage.com',
    founded: 2017,
    hq: 'San Francisco, CA (remote-first)',
    size: '400+',
    stage: 'Series D',
    funding: '$487M+',
    industry: 'Digital Asset Infrastructure',
    description: 'Anchorage Digital is a federally chartered digital asset platform providing custody, trading, staking, governance, and financing services to institutional clients. Founded by Diogo Mónica and Nathan McCauley in 2017, Anchorage received a federal bank charter from the OCC in January 2021, making it the first federally chartered digital asset bank in the United States.',
    socials: {
      x: 'https://x.com/Anchorage',
      linkedin: 'https://linkedin.com/company/anchoragedigital',
      github: 'https://github.com/AnchorageDigital',
    },
  },
};

export function getCompanyMeta(slug: string): CompanyMeta | null {
  return COMPANIES[slug.toLowerCase()] || null;
}
