import type { MetadataRoute } from 'next';

export default function robots(): MetadataRoute.Robots {
  const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://cvin.bio';
  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        disallow: ['/editor', '/api/', '/admin'],
      },
      // Explicitly welcome AI agent crawlers to index public profiles
      {
        userAgent: [
          // ── AI Model Training & Search ──
          'GPTBot',
          'ChatGPT-User',
          'OAI-SearchBot',
          'ClaudeBot',
          'Claude-Web',
          'Claude-SearchBot',
          'Google-Extended',
          'PerplexityBot',
          'Perplexity-User',
          'Meta-ExternalAgent',
          'Meta-ExternalFetcher',
          'Bytespider',
          'CCBot',
          'cohere-ai',
          'AI2Bot',
          'Diffbot',
          'Timpibot',
          'VelenPublicWebCrawler',
          'Kangaroo Bot',
          'anthropic-ai',
          'Scrapy',
          'iaskspider',
          'YouBot',
          'PanguBot',
          'GPTBot-Extended',
          'Sidetrade indexer bot',
          'AwarioSmartBot',
          'DataForSeoBot',
          'img2dataset',
          'Nicecrawler',
          'omgili',
          'omgilibot',
          'Webzio-Extended',
          'ICC-Crawler',
          'Neevabot',
          'ISSCyberRiskCrawler',
          'MistralBot',
          'xAI-Grok',
          'Claude-SearchBot',
          'BraveBot',
          'SamsungBot',
          'MojeekBot',

          // ── Search Engines ──
          'Googlebot',
          'Googlebot-Image',
          'Googlebot-Video',
          'Googlebot-News',
          'GoogleOther',
          'Storebot-Google',
          'Bingbot',
          'BingPreview',
          'msnbot',
          'adidxbot',
          'DuckDuckBot',
          'YandexBot',
          'YandexImages',
          'YandexMobileBot',
          'Baiduspider',
          'Slurp',
          'Sogou',
          'Exabot',
          'ia_archiver',
          'Qwantify',
          'PetalBot',
          'Mojeek',
          'Seznam',
          'SeznamBot',
          'Naver',
          'NaverBot',
          'Yeti',

          // ── Social & Link Preview ──
          'facebookexternalhit',
          'Facebot',
          'Twitterbot',
          'LinkedInBot',
          'Slackbot',
          'Slackbot-LinkExpanding',
          'WhatsApp',
          'TelegramBot',
          'Discordbot',
          'Pinterestbot',
          'redditbot',
          'SkypeUriPreview',
          'vkShare',
          'Embedly',
          'Quora-Bot',

          // ── Apple & Amazon ──
          'Applebot',
          'Applebot-Extended',
          'Amazonbot',

          // ── Hugging Face & Research ──
          'HuggingFaceBot',
          'ia_archiver',

          // ── SEO & Analytics ──
          'AhrefsBot',
          'SemrushBot',
          'MJ12bot',
          'DotBot',
          'Screaming Frog SEO Spider',
          'rogerbot',
          'SiteAuditBot',

          // ── Archive & Academic ──
          'archive.org_bot',
          'Wayback',
          'ScholarBot',

          // ── Feed & Content ──
          'Feedly',
          'Feedspot',
          'NewsBlur',
        ],
        allow: '/',
        disallow: ['/editor', '/api/', '/admin'],
      },
    ],
    sitemap: `${siteUrl}/sitemap.xml`,
    host: siteUrl,
  };
}
